@php
$isHomepage = request()->is('/');
@endphp

<!-- Main Navigation Bar -->
<nav id="main-navbar" class="fixed top-0 w-full z-50 transition-all duration-500 ease-out {{ $isHomepage ? 'bg-transparent' : 'bg-white border-b border-gray-200' }}">
    <div class="w-full px-6 lg:px-8">
        <div class="flex justify-between items-center h-20">
            
            <!-- Menu Button -->
            <button id="menu-button" class="transition-all duration-500 z-60 relative {{ $isHomepage ? 'text-white hover:text-gray-300' : 'text-black hover:text-gray-700' }}" aria-label="Toggle menu">
                <div class="relative w-6 h-6">
                    <svg id="menu-icon-open" class="h-6 w-6 absolute inset-0 transition-all duration-500 opacity-100 rotate-0" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/></svg>
                    <svg id="menu-icon-close" class="h-6 w-6 absolute inset-0 transition-all duration-500 opacity-0 -rotate-180" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" x2="6" y1="6" y2="18"/><line x1="6" x2="18" y1="6" y2="18"/></svg>
                </div>
            </button>

            <!-- Logo -->
            <a href="{{ url('/') }}" class="group z-60 absolute left-1/2 transform -translate-x-1/2">
                <span id="navbar-logo" class="text-xl font-bold tracking-tight transition-all duration-500 {{ $isHomepage ? 'text-white' : 'text-black' }}">
                    SINEMAKU PICTURES
                </span>
            </a>

            <!-- Search Button -->
            <button id="search-button" class="transition-all duration-500 z-60 relative {{ $isHomepage ? 'text-white hover:text-gray-300' : 'text-black hover:text-gray-700' }}" aria-label="Toggle search">
                <div class="relative w-6 h-6">
                    <svg id="search-icon-open" class="h-6 w-6 absolute inset-0 transition-all duration-500 opacity-100 rotate-0" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
                    <svg id="search-icon-close" class="h-6 w-6 absolute inset-0 transition-all duration-500 opacity-0 -rotate-180" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" x2="6" y1="6" y2="18"/><line x1="6" x2="18" y1="6" y2="18"/></svg>
                </div>
            </button>
        </div>
    </div>
</nav>

<!-- Full-Screen Mega Menu Overlay -->
<div id="mega-menus" class="fixed inset-0 z-40 transition-all duration-700 ease-in-out opacity-0 invisible">
    <div class="absolute inset-0 bg-black/95 backdrop-blur-2xl transition-all duration-700 opacity-0"></div>
    <div class="relative h-full overflow-y-auto transition-all duration-700 delay-200 opacity-0 translate-y-8">
        <div class="min-h-full flex items-center justify-center py-20">
            <div class="w-full px-6 lg:px-8">
                <!-- Menu content will be dynamically generated by JS if needed, or hardcoded -->
                @php
                    $navItems = [
                        ['name' => 'Home', 'path' => '/', 'description' => 'Return to homepage'],
                        ['name' => 'Films', 'path' => '/films', 'description' => 'Explore our cinematic works'],
                        ['name' => 'Series', 'path' => '/series', 'description' => 'Long-form storytelling'],
                        ['name' => 'Shop', 'path' => '/shop', 'description' => 'Exclusive merchandise'],
                        ['name' => 'Articles', 'path' => '/article', 'description' => 'Stories and insights'],
                        ['name' => 'Events', 'path' => '/events', 'description' => 'Premieres and screenings'],
                        ['name' => 'Membership', 'path' => '/membership', 'description' => 'Join our inner circle'],
                        ['name' => 'Careers', 'path' => '/careers', 'description' => 'Join our creative team'],
                    ];
                @endphp
                <div class="grid grid-cols-1 xl:grid-cols-12 gap-16 items-center">
                    <div class="xl:col-span-8">
                        <div class="space-y-4 md:space-y-6 lg:space-y-8">
                            @foreach ($navItems as $index => $item)
                                <div class="transition-all duration-700 opacity-0 -translate-x-8" style="transition-delay: 0ms;">
                                    <a href="{{ url($item['path']) }}" class="group block transition-all duration-500 {{ request()->is(ltrim($item['path'], '/')) ? 'text-white' : 'text-gray-400 hover:text-white' }}">
                                        <div class="flex flex-col lg:flex-row lg:items-baseline lg:space-x-6">
                                            <h2 class="text-4xl sm:text-5xl md:text-6xl lg:text-7xl xl:text-8xl cinematic-title tracking-tight group-hover:translate-x-2 lg:group-hover:translate-x-4 transition-transform duration-500">
                                                {{ $item['name'] }}
                                            </h2>
                                            <span class="text-sm md:text-base lg:text-lg editorial-text opacity-0 group-hover:opacity-100 transition-all duration-500 delay-100 mt-2 lg:mt-0">
                                                {{ $item['description'] }}
                                            </span>
                                        </div>
                                        <div class="h-px bg-gradient-to-r from-white to-transparent mt-2 md:mt-4 transition-all duration-700 {{ request()->is(ltrim($item['path'], '/')) ? 'w-16 md:w-32 opacity-100' : 'w-0 group-hover:w-12 md:group-hover:w-24 opacity-0 group-hover:opacity-50' }}"></div>
                                    </a>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="xl:col-span-4 mt-16 xl:mt-0">
                        <!-- Contact info etc. -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Search Modal Overlay -->
<div id="search-modal" class="fixed inset-0 z-40 transition-all duration-500 ease-in-out opacity-0 invisible">
    <div class="absolute inset-0 bg-black/95 backdrop-blur-2xl transition-all duration-500 opacity-0"></div>
    <div class="relative h-full transition-all duration-500 delay-100 opacity-0 translate-y-4">
        <div class="flex flex-col h-full">
            <div class="flex-shrink-0 pt-32 pb-8">
                <div class="max-w-4xl mx-auto px-6 lg:px-8">
                    <h2 class="text-4xl md:text-5xl cinematic-title text-white mb-8 text-center">
                        Search Sinemaku
                    </h2>
                    <form id="search-form" class="relative">
                        <input type="text" id="search-input" placeholder="Search films, series, events, articles, and careers..." class="w-full px-8 py-6 text-xl bg-white/10 backdrop-blur-sm border border-white/20 text-white placeholder-gray-400 focus:outline-none focus:border-white/40 transition-all duration-300 editorial-text" autofocus>
                        <button type="submit" class="absolute right-4 top-1/2 -translate-y-1/2 p-2 text-gray-400 hover:text-white transition-colors duration-300">
                            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
                        </button>
                    </form>
                </div>
            </div>
            <div class="flex-1 overflow-y-auto">
                <div id="search-results-container" class="max-w-4xl mx-auto px-6 lg:px-8 pb-20">
                    <!-- Search results will be populated here by JS -->
                </div>
            </div>
        </div>
    </div>
</div>
